language: node_js
node_js:
  - "14.16.0"
dist: trusty
cache: npm
before_install:
  - npm --version
branches:
  only:
    - master
env:
  - TEST_SUITE=lint
  - TEST_SUITE=test-unit-all-ci
  - TEST_SUITE=test-security
  - TEST_SUITE=test-integration
script:
  - npm run $TEST_SUITE
